language: c
compiler: gcc
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - cmake --build .
  - make install DESTDIR=/tmp/package-genmac
addons:
  apt:
    packages:
      - freeglut3-dev
      - libxmu-dev
      - asciidoc
      - xmlto
